export const UTILITY_MENU_TRANSITION_MS = 750

export const UTILITY_MENU_CASCADE_MS = UTILITY_MENU_TRANSITION_MS

export const UTILITY_MENU_CASCADE_ITEM_MS = 120

export const UTILITY_MENU_CASCADE_STAGGER_MS = 45

export const UTILITY_MENU_CLOSE_MS = UTILITY_MENU_TRANSITION_MS

export const UTILITY_MENU_TRANSITION = `${UTILITY_MENU_TRANSITION_MS}ms cubic-bezier(0.33, 1, 0.68, 1)`

export const UTILITY_MENU_CASCADE_ITEM = `${UTILITY_MENU_CASCADE_ITEM_MS}ms`

export const UTILITY_MENU_CASCADE_STAGGER = `${UTILITY_MENU_CASCADE_STAGGER_MS}ms`
